- hosts: all
  become: true
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      #cache_valid_time: 86400 
  - name: installing nginx software
    apt:
      name: nginx
      state: present

  - name: start nginx service
    service:
      name: nginx
      state: started